PT/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from PT import views
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.static import serve
from annonces.views import encherir

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.home,name = 'home'),
    url(r'^comptes/',include('comptes.urls')),      
    url(r'^annonces/',include('annonces.urls')),
    path('annonces/encherir/<int:idProduit>/',encherir),

    
    
   ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comptes/urls.py
from django.conf.urls import url
from django.urls import path
from comptes import views 
app_name = 'comptes'

urlpatterns = [
	url(r'^inscription/$',views.inscription, name ='inscription'),
	url(r'^connexion/$',views.connexion, name ='connexion'),
	url(r'^deconnexion/$',views.logout_user, name ='deconnexion'),
	url(r'^profil/$',views.profil, name ='profil'),
	path('supprimer/<int:pk>/', views.compte_supprimer, name ='compte_supprimer'),


	
]

PT/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from PIL import Image
from django.urls import reverse



class Vendeur(models.Model):
    numVendeur = models.OneToOneField(User,primary_key=True, on_delete=models.CASCADE)
    nomVendeur = models.CharField(max_length=30)
    prenomVendeur = models.CharField(max_length=30)
    mailVendeur = models.EmailField()
    photoVendeur = models.ImageField(default= 'default.jpg',upload_to= "photosdeprofil")

    def __str__(self):
        return f'{self.numVendeur.username} Vendeur' 

    class Meta:
        db_table ='vendeur'

"""def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

        img = Image.open(self.photoVendeur.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.photoVendeur.path)
"""
    


class Acheteur(models.Model):
    numAcheteur = models.OneToOneField(User,primary_key=True, on_delete=models.CASCADE)
    nomAcheteur = models.CharField(max_length=30)
    prenomAcheteur = models.CharField(max_length=30)
    mailAcheteur = models.EmailField()
    adresseAcheteur = models.TextField(null=True)
    photoAcheteur = models.ImageField(default= 'default.jpg',upload_to= "photosdeprofil",blank = True)

    def __str__(self):
        return f'{self.numAcheteur.username} Acheteur' 

class Produit(models.Model):
    Categorie_choices = [
    ('Véhicules', 'Véhicules'),
    ('Vacances', 'Vacances'),
    ('Loisirs', 'Loisirs'),
    ('Mode', 'Mode'),
    ('Multimédia', 'Multimédia'),
    ('Maison', 'Maison'),
    ('Autre', 'Autre'),
]
    numProduit = models.AutoField(primary_key=True)
    titre = models.CharField(max_length=30)
    description = models.TextField(verbose_name="Description du produit")
    images = models.ImageField(upload_to= "images", height_field=None)
    prixBase =  models.FloatField(validators=[MinValueValidator(0)],verbose_name="Mise à prix")
    totalEnchere =  models.FloatField(null=True,default=0,validators=[MinValueValidator(0)])
    dateDebut = models.DateTimeField(default=timezone.now, verbose_name="Date de début de l'enchère")
    dateFin = models.DateTimeField(verbose_name="Date de fin de l'enchère")
    vendeurFK = models.ForeignKey(Vendeur, on_delete=models.CASCADE, db_column='numVendeur')
    acheteurFK = models.ForeignKey(Acheteur,null=True,blank=True, on_delete=models.CASCADE, db_column='acheteurFK')
    categorie = models.CharField(max_length=30, choices=Categorie_choices)

    def __str__(self):
        return f'{self.titre}'

    def get_absolute_url(self):
        return reverse('produit_detail', kwargs={'pk': self.pk})
        
""" def save(self,*args,**kwargs):
        if self.images:
            super().save(*args,**kwargs)

            img = Image.open(self.images.path)

            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.images.path)
"""
    


class Enchere(models.Model):
    acheteurFK = models.ForeignKey(Acheteur, on_delete=models.CASCADE, db_column='numAcheteur')
    produitFK = models.ForeignKey(Produit, on_delete=models.CASCADE, db_column='numProduit')
    numEnchere = models.AutoField(primary_key=True)
    moment = models.DateTimeField(auto_now_add=True)
    montant = models.DecimalField(max_digits=6, decimal_places=1,validators=[MinValueValidator(0.5)],verbose_name="Montant de l'enchère")
    commentaire = models.CharField(max_length=50,null=True)
    

    class Meta:
        db_table = 'Enchere'
    

PT/forms.py
from django import forms
from django.forms import ModelChoiceField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from PT.models import *
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator




class ConnexionForm(forms.Form):
    username = forms.CharField(max_length=254)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

# Formulaire d'inscription ou de modification d'un acheteur
class AcheteurForm(UserCreationForm):
    adresseAcheteur = forms.CharField(max_length=254)
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password1', 'password2' )

# Formulaire d'inscription ou de modification d'un vendeur
class VendeurForm(forms.ModelForm):
    class Meta:
        model = Vendeur
        fields = ['photoVendeur']

# Formulaire de création ou de modification d'un produit
class ProduitForm(forms.Form):
    Categorie_choices = (
        ('Emploi', 'Véhicules'),
        ('Vacances', 'Loisirs'),
        ('Mode', 'Multimédia'),
        ('Maison', 'Autre')
    )
    titre = forms.CharField(max_length=30)
    description = forms.CharField(max_length=254)
    images = forms.ImageField(max_length=400,required = False)
    prixBase =  forms.FloatField(validators=[MinValueValidator(0)])
    dateDebut = forms.DateTimeField(label="Date de début de l'enchère")
    dateFin = forms.DateTimeField()
    categorie = forms.ChoiceField(label="Catégorie",choices=Categorie_choices)

# Formulaire de création d'une enchère
class EnchereForm(forms.Form):
    montant = forms.FloatField(validators=[MinValueValidator(0.5)])
    commentaire = forms.CharField(max_length=50)


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(label="Adresse électronique")
    class Meta:
        model = User
        fields = ['username','email' ]


# Formulaire d'inscription
class InscriptionForm(UserCreationForm):
    photo = forms.ImageField(required=False)
    adresse = forms.CharField(widget=forms.Textarea,required=False)
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password1', 'password2' )

PT/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404 
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage
from PT.forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.utils import timezone

def home(request):

    # Pour un vendeur on lui affiche ses ventes et/ou ses invendus et/ou ses annonces sur la page d'accueil
    mes_annonces = []
    ventes = []
    invendus = []
    produits_encheris=[]
    encheres_gagnees =[]
    encheres = []
    if request.user.is_authenticated:
        # Pour un vendeur ses ventes
        for i in Produit.objects.filter(vendeurFK=request.user.vendeur,dateFin__lte = timezone.now(),totalEnchere__gt=0):
            ventes.append(i)
        # ses invendus
        for j in Produit.objects.filter(vendeurFK=request.user.vendeur,dateFin__lte = timezone.now(),totalEnchere=0):
            invendus.append(j)
        # ses annonces en cours
        for k in Produit.objects.filter(vendeurFK=request.user.vendeur,dateFin__gt = timezone.now()):
            mes_annonces.append(k)
        # Pour un acheteur ses encheres remportées       
        for a in Produit.objects.filter(acheteurFK=request.user.acheteur,dateFin__lte=timezone.now()):
            enchere_gagnees.append(a)
        # les produits auxquels il a enchéri
        for c in Enchere.objects.filter(acheteurFK=request.user.acheteur):
            encheres.append(c.produitFK)

    return render(request, 'home.html',locals())

PT/templates/base.html
{% load static%}

<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">

	<title>Polyenchère</title>
</head>
<body>
	<header class="site-header">
		<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
			<div class="container">
				<a class="navbar-brand mr-4" href="/">MON ENCHÈRE</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarToggle">
					<div class="navbar-nav mr-auto">
						<a class="nav-item nav-link" href=" {% url 'home'%}">Accueil</a>
						{% if user.is_authenticated %}
						<a class="nav-item nav-link" href=" {% url 'mes_annonces'%}">Mes annonces</a>
						<div class="dropdown">
							{% endif %}
							<a class="btn  nav-item nav-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Annonces
							</a>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
								<a class="dropdown-item" href="{% url 'liste_produits' %}">Toutes les annonces</a>
								<a class="dropdown-item" href="{% url 'produits_categorie' 'Maison' %}">Maison</a>
								<a class="dropdown-item" href="{% url 'produits_categorie' 'Mode' %}">Mode</a>
								<a class="dropdown-item" href="{% url 'produits_categorie' 'Multimédia' %}">Multimédia</a>
								<a class="dropdown-item" href="{% url 'produits_categorie' 'Loisirs' %}">Loisirs</a>
								<a class="dropdown-item" href="{% url 'produits_categorie' 'Vacances' %}">Vacances</a>
								<a class="dropdown-item" href="{% url 'produits_categorie' 'Véhicules' %}">Véhicules</a>
								<a class="dropdown-item" href="{% url 'produits_categorie' 'Autres' %}">Autres</a>
							</div>
						</div>
						{% if user.is_authenticated %}
					<a class="nav-item nav-link" href="{% url 'produit_ajouter' %}">Ajouter une annonce</a>
					{% endif %}
					</div>

					<!-- Navbar Right Side -->
					<div class="navbar-nav">
						{% if user.is_authenticated %}
						<a class="nav-item nav-link" href="{% url 'comptes:deconnexion' %}">Déconnexion</a>
						<a class="nav-item nav-link" href="{% url 'comptes:profil' %}">Profil</a>

						{% else %}
						<a class="nav-item nav-link" href="{% url 'comptes:connexion' %}">Connexion</a>
						<a class="nav-item nav-link" href="{% url 'comptes:inscription' %}">Inscription</a>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>
	</header>
	<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
    	{% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
      {% block content %}{% endblock %}
    </div>
    
</main>
	

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>

PT/templates/home.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}
{% if mes_annonces %}
<h3>Mes annonces :</h3>
  {% for produit in mes_annonces %}


<div class="card mb-3 mw-75 mt-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{{ produit.images.url }}" class="card-img">
    </div>
    <div class="col-md-8">
      <img class="rounded-circle float-right article-img mt-3" src="{{ produit.vendeurFK.photoVendeur.url }}">
      <div class="card-body">
        <h5 class="card-title" ><a href="{%  url 'produit_detail' produit.numProduit %}">{{ produit.titre }}</a></h5>
        <p class="card-text overflow-hidden"></p>
        <p class="card-text"><small class="text-muted">Fin de l'enchère: {{ produit.dateFin }}</small></p>
      </div>
    </div>
  </div>
</div>


{% endfor %}
{% endif %}
{% if ventes %}
<h3>Mes ventes :</h3>
{% for produit in ventes %}
<div class="card mb-3 mw-75" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{{ produit.images.url }}" class="card-img">
    </div>
    <div class="col-md-8">
      <img class="rounded-circle float-right article-img mt-3" src="{{ produit.vendeurFK.photoVendeur.url }}">
      <div class="card-body">
        <h5 class="card-title" ><a href="{%  url 'produit_detail' produit.numProduit %}">{{ produit.titre }}</a></h5>
        <p class="card-text overflow-hidden"></p>
        <p class="card-text"><small class="text-muted">Fin de l'enchère: {{ produit.dateFin }}</small></p>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endif %}
{% if invendus%}
<h3>Mes produits invendus :</h3>
{% for produit in invendus %}
<div class="card mb-3 mw-75" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{{ produit.images.url }}" class="card-img">
    </div>
    <div class="col-md-8">
      <img class="rounded-circle float-right article-img mt-3" src="{{ produit.vendeurFK.photoVendeur.url }}">
      <div class="card-body">
        <h5 class="card-title" ><a href="{%  url 'produit_detail' produit.numProduit %}">{{ produit.titre }}</a></h5>
        <p class="card-text overflow-hidden"></p>
        <p class="card-text"><small class="text-muted">Fin de l'enchère: {{ produit.dateFin }}</small></p>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endif %}

{% if encheres_gagnes %}
<h3>Mes enchères remportées :</h3>
{% for produit in encheres_gagnes %}
<div class="card mb-3 mw-75" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{{ produit.images.url }}" class="card-img">
    </div>
    <div class="col-md-8">
      <img class="rounded-circle float-right article-img mt-3" src="{{ produit.vendeurFK.photoVendeur.url }}">
      <div class="card-body">
        <h5 class="card-title" ><a href="{%  url 'produit_detail' produit.numProduit %}">{{ produit.titre }}</a></h5>
        <p class="card-text overflow-hidden"></p>
        <p class="card-text"><small class="text-muted">Fin de l'enchère: {{ produit.dateFin }}</small></p>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endif %}

      {% endif %}
{% endblock content %}