PT/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from PT import views
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.static import serve
from annonces.views import encherir

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.home,name = 'home'),
    url(r'^comptes/',include('comptes.urls')),      
    url(r'^annonces/',include('annonces.urls')),
    path('annonces/encherir/<int:idProduit>/',encherir),

    
    
   ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comptes/urls.py
from django.conf.urls import url
from django.urls import path
from comptes import views 
app_name = 'comptes'

urlpatterns = [
	url(r'^inscription/$',views.inscription, name ='inscription'),
	url(r'^connexion/$',views.connexion, name ='connexion'),
	url(r'^deconnexion/$',views.logout_user, name ='deconnexion'),
	url(r'^profil/$',views.profil, name ='profil'),
	path('supprimer/<int:pk>/', views.compte_supprimer, name ='compte_supprimer'),


	
]

PT/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from PIL import Image
from django.urls import reverse



class Vendeur(models.Model):
    numVendeur = models.OneToOneField(User,primary_key=True, on_delete=models.CASCADE)
    nomVendeur = models.CharField(max_length=30)
    prenomVendeur = models.CharField(max_length=30)
    mailVendeur = models.EmailField()
    photoVendeur = models.ImageField(default= 'default.jpg',upload_to= "photosdeprofil")

    def __str__(self):
        return f'{self.numVendeur.username} Vendeur' 

    class Meta:
        db_table ='vendeur'

"""def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

        img = Image.open(self.photoVendeur.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.photoVendeur.path)
"""
    


class Acheteur(models.Model):
    numAcheteur = models.OneToOneField(User,primary_key=True, on_delete=models.CASCADE)
    nomAcheteur = models.CharField(max_length=30)
    prenomAcheteur = models.CharField(max_length=30)
    mailAcheteur = models.EmailField()
    adresseAcheteur = models.TextField(null=True)
    photoAcheteur = models.ImageField(default= 'default.jpg',upload_to= "photosdeprofil",blank = True)

    def __str__(self):
        return f'{self.numAcheteur.username} Acheteur' 

class Produit(models.Model):
    Categorie_choices = [
    ('Véhicules', 'Véhicules'),
    ('Vacances', 'Vacances'),
    ('Loisirs', 'Loisirs'),
    ('Mode', 'Mode'),
    ('Multimédia', 'Multimédia'),
    ('Maison', 'Maison'),
    ('Autre', 'Autre'),
]
    numProduit = models.AutoField(primary_key=True)
    titre = models.CharField(max_length=30)
    description = models.TextField(verbose_name="Description du produit")
    images = models.ImageField(upload_to= "images", height_field=None)
    prixBase =  models.FloatField(validators=[MinValueValidator(0)],verbose_name="Mise à prix")
    totalEnchere =  models.FloatField(null=True,default=0,validators=[MinValueValidator(0)])
    dateDebut = models.DateTimeField(default=timezone.now, verbose_name="Date de début de l'enchère")
    dateFin = models.DateTimeField(verbose_name="Date de fin de l'enchère")
    vendeurFK = models.ForeignKey(Vendeur, on_delete=models.CASCADE, db_column='numVendeur')
    acheteurFK = models.ForeignKey(Acheteur,null=True,blank=True, on_delete=models.CASCADE, db_column='acheteurFK')
    categorie = models.CharField(max_length=30, choices=Categorie_choices)

    def __str__(self):
        return f'{self.titre}'

    def get_absolute_url(self):
        return reverse('produit_detail', kwargs={'pk': self.pk})
        
""" def save(self,*args,**kwargs):
        if self.images:
            super().save(*args,**kwargs)

            img = Image.open(self.images.path)

            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.images.path)
"""
    


class Enchere(models.Model):
    acheteurFK = models.ForeignKey(Acheteur, on_delete=models.CASCADE, db_column='numAcheteur')
    produitFK = models.ForeignKey(Produit, on_delete=models.CASCADE, db_column='numProduit')
    numEnchere = models.AutoField(primary_key=True)
    moment = models.DateTimeField(auto_now_add=True)
    montant = models.DecimalField(max_digits=6, decimal_places=1,validators=[MinValueValidator(0.5)],verbose_name="Montant de l'enchère")
    commentaire = models.CharField(max_length=50,null=True)
    

    class Meta:
        db_table = 'Enchere'
    

comptes/models.py
from django.db import models

# Create your models here.

PT/forms.py
from django import forms
from django.forms import ModelChoiceField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from PT.models import *
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator




class ConnexionForm(forms.Form):
    username = forms.CharField(max_length=254)
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

# Formulaire d'inscription ou de modification d'un acheteur
class AcheteurForm(UserCreationForm):
    adresseAcheteur = forms.CharField(max_length=254)
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password1', 'password2' )

# Formulaire d'inscription ou de modification d'un vendeur
class VendeurForm(forms.ModelForm):
    class Meta:
        model = Vendeur
        fields = ['photoVendeur']

# Formulaire de création ou de modification d'un produit
class ProduitForm(forms.Form):
    Categorie_choices = (
        ('Emploi', 'Véhicules'),
        ('Vacances', 'Loisirs'),
        ('Mode', 'Multimédia'),
        ('Maison', 'Autre')
    )
    titre = forms.CharField(max_length=30)
    description = forms.CharField(max_length=254)
    images = forms.ImageField(max_length=400,required = False)
    prixBase =  forms.FloatField(validators=[MinValueValidator(0)])
    dateDebut = forms.DateTimeField(label="Date de début de l'enchère")
    dateFin = forms.DateTimeField()
    categorie = forms.ChoiceField(label="Catégorie",choices=Categorie_choices)

# Formulaire de création d'une enchère
class EnchereForm(forms.Form):
    montant = forms.FloatField(validators=[MinValueValidator(0.5)])
    commentaire = forms.CharField(max_length=50)


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(label="Adresse électronique")
    class Meta:
        model = User
        fields = ['username','email' ]


# Formulaire d'inscription
class InscriptionForm(UserCreationForm):
    photo = forms.ImageField(required=False)
    adresse = forms.CharField(widget=forms.Textarea,required=False)
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password1', 'password2' )

PT/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404 
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage
from PT.forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.utils import timezone

def home(request):

    # Pour un vendeur on lui affiche ses ventes et/ou ses invendus et/ou ses annonces sur la page d'accueil
    mes_annonces = []
    ventes = []
    invendus = []
    produits_encheris=[]
    encheres_gagnees =[]
    encheres = []
    if request.user.is_authenticated:
        # Pour un vendeur ses ventes
        for i in Produit.objects.filter(vendeurFK=request.user.vendeur,dateFin__lte = timezone.now(),totalEnchere__gt=0):
            ventes.append(i)
        # ses invendus
        for j in Produit.objects.filter(vendeurFK=request.user.vendeur,dateFin__lte = timezone.now(),totalEnchere=0):
            invendus.append(j)
        # ses annonces en cours
        for k in Produit.objects.filter(vendeurFK=request.user.vendeur,dateFin__gt = timezone.now()):
            mes_annonces.append(k)
        # Pour un acheteur ses encheres remportées       
        for a in Produit.objects.filter(acheteurFK=request.user.acheteur,dateFin__lte=timezone.now()):
            enchere_gagnees.append(a)
        # les produits auxquels il a enchéri
        for c in Enchere.objects.filter(acheteurFK=request.user.acheteur):
            encheres.append(c.produitFK)

    return render(request, 'home.html',locals())

comptes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage
from PT.forms import *
from PT.models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DeleteView
from django.contrib.auth.forms import UserCreationForm


def inscription(request):
    if request.method == 'POST':
        form = InscriptionForm(request.POST,request.FILES)
        if form.is_valid():
            form.save() #Sauvegarde/Creation d'un utilisateur de base
            username = form.cleaned_data.get('username')
            mail = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
             #Authentification de l'utilisateur
            user = authenticate(username=username, password=raw_password)
            Utilisateur = User.objects.get(username=username)
            #On crée un vendeur
            if(form.cleaned_data.get('photo') == None) :
                photo='default.jpg'
            else :
                photo=form.cleaned_data.get('photo')
            vendeur = Vendeur(numVendeur=Utilisateur,nomVendeur=form.cleaned_data.get('last_name'),prenomVendeur=form.cleaned_data.get('first_name'), mailVendeur=form.cleaned_data.get('email'),photoVendeur=photo)
            vendeur.save()
            #On crée un acheteur 
            acheteur = Acheteur(numAcheteur=Utilisateur,nomAcheteur=form.cleaned_data.get('last_name'),prenomAcheteur=form.cleaned_data.get('first_name'), mailAcheteur=form.cleaned_data.get('email'),photoAcheteur=photo,adresseAcheteur=form.cleaned_data.get('adresse'))
            acheteur.save()
            login(request, user) #Connexion au site
            messages.success(request, f'Vous êtes inscrits {username}!')
            return redirect('home')
    else:
        form = InscriptionForm()
    return render(request,'comptes/inscription.html',{'form':form})


def connexion(request):
    if request.method == 'POST':
        form = ConnexionForm(data=request.POST)
        if form.is_valid():
		# On récupère et connecte l'utilisateur
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user:
                login(request,user)
                return redirect('home')
            else :
                messages.warning(request, f'Utilisateur inconnu ou mauvais de mot de passe.')


    else:
        form = ConnexionForm()
    return render(request,'comptes/connexion.html',{'form':form})

@login_required
def logout_user(request):
    logout(request)
    return render(request, 'comptes/deconnexion.html')


@login_required
def profil(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        form = VendeurForm(request.POST,request.FILES, instance=request.user.vendeur)
        if form.is_valid() and u_form.is_valid():
            form.save()
            u_form.save()
            messages.success(request, f'Votre compte a bien été modifié !')
            return redirect('comptes:profil')

    else:
        form = VendeurForm()
        u_form = UserUpdateForm()

    return render(request, 'comptes/profil.html', {"form":form,"u_form":u_form})

class VendeurDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Vendeur
    template_name = 'comptes/compte_supprimer.html'
    success_url = '/'


def compte_supprimer(request,pk):
    if request.method =="POST":
        request.user.delete()
        logout(request)
        return redirect('home')

    return render(request, 'comptes/compte_supprimer.html')

PT/templates/comptes/compte_supprimer.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Supprimer votre compte</legend>
                <h2>Êtes-vous sûr de vouloir supprimer votre compte ? "{{ user.username }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit" >Oui, Supprimer</button>
                <a class="btn btn-outline-secondary" href="{% url 'home' %}">Annuler</a>
            </div>
        </form>
    </div>
{% endblock content %}

PT/templates/comptes/connexion.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="content-section">
  <form method="post" action="">
    {% csrf_token %}
    
    <fieldset class="form-group"> 
      <legend class="border-bottom mb-4">Connexion
      </legend>
      {{form|crispy}}
    </fieldset>
      <button class="btn btn-outline-info" type="submit">Se connecter</button>
    </div>
  </form>
<div class="border-top pt-3">
            <small class="text-muted">
                Pas encore inscrit ? <a class="ml-2" href="{% url 'comptes:inscription' %}">S'inscrire</a>
            </small>
        </div>
    </div>

{% endblock %}

PT/templates/comptes/deconnexion.html
{% extends "base.html" %}
{% block content %}
    <h2>Vous avez été deconnecté</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'comptes:connexion' %}">Se connecter</a>
        </small>
    </div>
{% endblock content %}

PT/templates/comptes/inscription.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="content-section">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <fieldset class="form-group"> 
      <legend class="border-bottom mb-4">Inscription
      </legend>

      {{form|crispy}}
    </fieldset>
      <button class="btn btn-outline-info" type="submit">S'incrire</button>
    </div>
  </form>
<div class="border-top pt-3">
            <small class="text-muted">
                Vous avez déjà un compte ? <a class="ml-2" href="{% url 'comptes:connexion' %}">Se connecter</a>
            </small>
        </div>
    </div>

{% endblock %}

PT/templates/comptes/profil.html
{% extends "base.html" %}

{% block content %}
{% load crispy_forms_tags %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.vendeur.photoVendeur.url }}">
    <div class="media-body">
      <h2 class="account-heading">{{ user.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
    </div>
  </div>
  <!-- FORM HERE -->
  <form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    
    <fieldset class="form-group"> 
      <legend class="border-bottom mb-4">Profil
      </legend>
      {{u_form|crispy}}
      {{form|crispy}}

    </fieldset>
    <button class="btn btn-outline-info" type="submit">Modifier</button>
  </div>
</form>
<a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'comptes:compte_supprimer' user.id %}">Supprimer</a>
</div>
{% endblock content %}

PT/templates/comptes/update_vendeur.html
 {% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="content-section">
  <form method="post" action="">
    {% csrf_token %}
    
    <fieldset class="form-group"> 
      <legend class="border-bottom mb-4">Inscription
      </legend>
      {{form|crispy}}
    </fieldset>
      <button class="btn btn-outline-info" type="submit">S'incrire</button>
    </div>
  </form>
<div class="border-top pt-3">
            <small class="text-muted">
                Vous avez déjà un compte ? <a class="ml-2" href="{% url 'comptes:connexion' %}">Se connecter</a>
            </small>
        </div>
    </div>

{% endblock %}

PT/templates/comptes/vendeur_supprimer.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Supprimer votre compte</legend>
                <h2>Êtes-vous sûr de vouloir supprimer votre compte ? "{{ user.username }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Oui, Supprimer</button>
                <a class="btn btn-outline-secondary" href="{% url 'home' %}">Annuler</a>
            </div>
        </form>
    </div>
{% endblock content %}